// Mocks generated by Mockito (manually created due to build_runner issues)
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:typed_data' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ai_bookkeeping/services/tts_service.dart' as _i3;
import 'package:ai_bookkeeping/services/streaming_tts_service.dart' as _i4;

/// A class which mocks [TTSEngine].
class MockTTSEngine extends _i1.Mock implements _i3.TTSEngine {
  @override
  Future<void> initialize() async {}

  @override
  Future<void> speak(String? text) async {}

  @override
  Future<void> stop() async {}

  @override
  Future<void> pause() async {}

  @override
  Future<void> resume() async {}

  @override
  Future<void> setRate(double? rate) async {}

  @override
  Future<void> setVolume(double? volume) async {}

  @override
  Future<void> setPitch(double? pitch) async {}

  @override
  Future<void> setLanguage(String? language) async {}

  @override
  Future<void> setVoice(String? voiceName) async {}

  @override
  Future<List<_i3.TTSVoice>> getAvailableVoices() async => [];

  @override
  Future<_i2.Uint8List?> synthesize(String? text) async => null;

  @override
  void dispose() {}
}

/// A class which mocks [StreamingTTSService].
class MockStreamingTTSService extends _i1.Mock
    implements _i4.StreamingTTSService {}
