// Mocks generated by Mockito 5.4.6 from annotations
// in ai_bookkeeping/test/services/tts_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:ai_bookkeeping/services/streaming_tts_service.dart' as _i5;
import 'package:ai_bookkeeping/services/tts_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [TTSEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockTTSEngine extends _i1.Mock implements _i2.TTSEngine {
  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speak(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setRate(double? rate) =>
      (super.noSuchMethod(
            Invocation.method(#setRate, [rate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setLanguage(String? language) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguage, [language]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVoice(String? voiceName) =>
      (super.noSuchMethod(
            Invocation.method(#setVoice, [voiceName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.TTSVoice>> getAvailableVoices() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableVoices, []),
            returnValue: _i3.Future<List<_i2.TTSVoice>>.value(<_i2.TTSVoice>[]),
            returnValueForMissingStub: _i3.Future<List<_i2.TTSVoice>>.value(
              <_i2.TTSVoice>[],
            ),
          )
          as _i3.Future<List<_i2.TTSVoice>>);

  @override
  _i3.Future<_i4.Uint8List?> synthesize(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#synthesize, [text]),
            returnValue: _i3.Future<_i4.Uint8List?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Uint8List?>.value(),
          )
          as _i3.Future<_i4.Uint8List?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StreamingTTSService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStreamingTTSService extends _i1.Mock
    implements _i5.StreamingTTSService {
  @override
  _i3.Stream<_i5.StreamingTTSState> get stateStream =>
      (super.noSuchMethod(
            Invocation.getter(#stateStream),
            returnValue: _i3.Stream<_i5.StreamingTTSState>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i5.StreamingTTSState>.empty(),
          )
          as _i3.Stream<_i5.StreamingTTSState>);

  @override
  bool get isSpeaking =>
      (super.noSuchMethod(
            Invocation.getter(#isSpeaking),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(
            Invocation.getter(#isInitialized),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speak(String? text, {bool? interrupt = true}) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text], {#interrupt: interrupt}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> fadeOutAndStop({
    Duration? duration = const Duration(milliseconds: 100),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fadeOutAndStop, [], {#duration: duration}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void setVoice(String? voice) => super.noSuchMethod(
    Invocation.method(#setVoice, [voice]),
    returnValueForMissingStub: null,
  );

  @override
  void setRate(double? rate) => super.noSuchMethod(
    Invocation.method(#setRate, [rate]),
    returnValueForMissingStub: null,
  );

  @override
  void setVolume(double? volume) => super.noSuchMethod(
    Invocation.method(#setVolume, [volume]),
    returnValueForMissingStub: null,
  );

  @override
  void setPitch(double? pitch) => super.noSuchMethod(
    Invocation.method(#setPitch, [pitch]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
