// Mocks generated by Mockito (manually created due to build_runner issues)
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: subtype_of_sealed_class

import 'package:mockito/mockito.dart' as _i1;
import 'package:ai_bookkeeping/services/voice/voice_intent_router.dart' as _i2;
import 'package:ai_bookkeeping/services/voice_feedback_system.dart' as _i3;
import 'package:ai_bookkeeping/services/voice/entity_disambiguation_service.dart' as _i4;
import 'package:ai_bookkeeping/services/voice/voice_delete_service.dart' as _i5;
import 'package:ai_bookkeeping/services/voice/voice_modify_service.dart' as _i6;
import 'package:ai_bookkeeping/services/voice_recognition_engine.dart' as _i7;
import 'package:ai_bookkeeping/services/tts_service.dart' as _i8;
import 'package:ai_bookkeeping/services/voice_navigation_service.dart' as _i9;
import 'package:ai_bookkeeping/services/database_service.dart' as _i10;

/// A class which mocks [VoiceIntentRouter].
class MockVoiceIntentRouter extends _i1.Mock implements _i2.VoiceIntentRouter {}

/// A class which mocks [VoiceFeedbackSystem].
class MockVoiceFeedbackSystem extends _i1.Mock
    implements _i3.VoiceFeedbackSystem {}

/// A class which mocks [EntityDisambiguationService].
class MockEntityDisambiguationService extends _i1.Mock
    implements _i4.EntityDisambiguationService {}

/// A class which mocks [VoiceDeleteService].
class MockVoiceDeleteService extends _i1.Mock
    implements _i5.VoiceDeleteService {}

/// A class which mocks [VoiceModifyService].
class MockVoiceModifyService extends _i1.Mock
    implements _i6.VoiceModifyService {}

/// A class which mocks [VoiceRecognitionEngine].
class MockVoiceRecognitionEngine extends _i1.Mock
    implements _i7.VoiceRecognitionEngine {}

/// A class which mocks [TTSService].
class MockTTSService extends _i1.Mock implements _i8.TTSService {}

/// A class which mocks [VoiceNavigationService].
class MockVoiceNavigationService extends _i1.Mock
    implements _i9.VoiceNavigationService {}

/// A class which mocks [DatabaseService].
class MockDatabaseService extends _i1.Mock implements _i10.DatabaseService {}
