// Mocks generated by Mockito 5.4.6 from annotations
// in ai_bookkeeping/test/services/voice_services_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i4;

import 'package:ai_bookkeeping/services/tts_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTTSSettings_0 extends _i1.SmartFake implements _i2.TTSSettings {
  _FakeTTSSettings_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TTSService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTTSService extends _i1.Mock implements _i2.TTSService {
  @override
  bool get isSpeaking =>
      (super.noSuchMethod(
            Invocation.getter(#isSpeaking),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Stream<_i2.TTSSpeakingState> get speakingStream =>
      (super.noSuchMethod(
            Invocation.getter(#speakingStream),
            returnValue: _i3.Stream<_i2.TTSSpeakingState>.empty(),
            returnValueForMissingStub: _i3.Stream<_i2.TTSSpeakingState>.empty(),
          )
          as _i3.Stream<_i2.TTSSpeakingState>);

  @override
  _i2.TTSSettings get currentSettings =>
      (super.noSuchMethod(
            Invocation.getter(#currentSettings),
            returnValue: _FakeTTSSettings_0(
              this,
              Invocation.getter(#currentSettings),
            ),
            returnValueForMissingStub: _FakeTTSSettings_0(
              this,
              Invocation.getter(#currentSettings),
            ),
          )
          as _i2.TTSSettings);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speak(String? text, {bool? interrupt = true}) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text], {#interrupt: interrupt}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speakTransactionResult({
    required String? type,
    required double? amount,
    String? category,
    String? merchant,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#speakTransactionResult, [], {
              #type: type,
              #amount: amount,
              #category: category,
              #merchant: merchant,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speakQueryResult({
    required String? period,
    required double? total,
    int? count,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#speakQueryResult, [], {
              #period: period,
              #total: total,
              #count: count,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speakAnomaly({
    required String? type,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#speakAnomaly, [], {
              #type: type,
              #message: message,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speakHelp() =>
      (super.noSuchMethod(
            Invocation.method(#speakHelp, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSettings(_i2.TTSSettings? newSettings) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettings, [newSettings]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setSpeechRate(double? rate) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeechRate, [rate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i2.TTSVoice>> getAvailableVoices() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableVoices, []),
            returnValue: _i3.Future<List<_i2.TTSVoice>>.value(<_i2.TTSVoice>[]),
            returnValueForMissingStub: _i3.Future<List<_i2.TTSVoice>>.value(
              <_i2.TTSVoice>[],
            ),
          )
          as _i3.Future<List<_i2.TTSVoice>>);

  @override
  _i3.Future<_i4.Uint8List?> synthesize(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#synthesize, [text]),
            returnValue: _i3.Future<_i4.Uint8List?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Uint8List?>.value(),
          )
          as _i3.Future<_i4.Uint8List?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
