// Mocks generated by Mockito 5.4.6 from annotations
// in ai_bookkeeping/test/services/voice_recognition_engine_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i5;

import 'package:ai_bookkeeping/services/voice_recognition_engine.dart' as _i2;
import 'package:ai_bookkeeping/services/voice_token_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeASRResult_0 extends _i1.SmartFake implements _i2.ASRResult {
  _FakeASRResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVoiceTokenInfo_1 extends _i1.SmartFake
    implements _i3.VoiceTokenInfo {
  _FakeVoiceTokenInfo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVoiceServiceStatus_2 extends _i1.SmartFake
    implements _i3.VoiceServiceStatus {
  _FakeVoiceServiceStatus_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AliCloudASRService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAliCloudASRService extends _i1.Mock
    implements _i2.AliCloudASRService {
  @override
  void setHotWords(List<_i2.HotWord>? hotWords) => super.noSuchMethod(
    Invocation.method(#setHotWords, [hotWords]),
    returnValueForMissingStub: null,
  );

  @override
  void addHotWords(List<_i2.HotWord>? hotWords) => super.noSuchMethod(
    Invocation.method(#addHotWords, [hotWords]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.ASRResult> transcribe(_i2.ProcessedAudio? audio) =>
      (super.noSuchMethod(
            Invocation.method(#transcribe, [audio]),
            returnValue: _i4.Future<_i2.ASRResult>.value(
              _FakeASRResult_0(this, Invocation.method(#transcribe, [audio])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ASRResult>.value(
              _FakeASRResult_0(this, Invocation.method(#transcribe, [audio])),
            ),
          )
          as _i4.Future<_i2.ASRResult>);

  @override
  _i4.Stream<_i2.ASRPartialResult> transcribeStream(
    _i4.Stream<_i5.Uint8List>? audioStream,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#transcribeStream, [audioStream]),
            returnValue: _i4.Stream<_i2.ASRPartialResult>.empty(),
            returnValueForMissingStub: _i4.Stream<_i2.ASRPartialResult>.empty(),
          )
          as _i4.Stream<_i2.ASRPartialResult>);

  @override
  _i4.Future<void> stopTranscription() =>
      (super.noSuchMethod(
            Invocation.method(#stopTranscription, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelTranscription() =>
      (super.noSuchMethod(
            Invocation.method(#cancelTranscription, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [LocalWhisperService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalWhisperService extends _i1.Mock
    implements _i2.LocalWhisperService {
  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ASRResult> transcribe(_i2.ProcessedAudio? audio) =>
      (super.noSuchMethod(
            Invocation.method(#transcribe, [audio]),
            returnValue: _i4.Future<_i2.ASRResult>.value(
              _FakeASRResult_0(this, Invocation.method(#transcribe, [audio])),
            ),
            returnValueForMissingStub: _i4.Future<_i2.ASRResult>.value(
              _FakeASRResult_0(this, Invocation.method(#transcribe, [audio])),
            ),
          )
          as _i4.Future<_i2.ASRResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NetworkChecker].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkChecker extends _i1.Mock implements _i2.NetworkChecker {
  @override
  _i4.Stream<bool> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i4.Stream<bool>.empty(),
            returnValueForMissingStub: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Future<bool> isOnline() =>
      (super.noSuchMethod(
            Invocation.method(#isOnline, []),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}

/// A class which mocks [VoiceTokenService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceTokenService extends _i1.Mock implements _i3.VoiceTokenService {
  @override
  _i4.Future<void> initialize({
    required String? baseUrl,
    required String? authToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {
              #baseUrl: baseUrl,
              #authToken: authToken,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void updateAuthToken(String? authToken) => super.noSuchMethod(
    Invocation.method(#updateAuthToken, [authToken]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i3.VoiceTokenInfo> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<_i3.VoiceTokenInfo>.value(
              _FakeVoiceTokenInfo_1(this, Invocation.method(#getToken, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i3.VoiceTokenInfo>.value(
              _FakeVoiceTokenInfo_1(this, Invocation.method(#getToken, [])),
            ),
          )
          as _i4.Future<_i3.VoiceTokenInfo>);

  @override
  _i4.Future<_i3.VoiceServiceStatus> checkServiceStatus() =>
      (super.noSuchMethod(
            Invocation.method(#checkServiceStatus, []),
            returnValue: _i4.Future<_i3.VoiceServiceStatus>.value(
              _FakeVoiceServiceStatus_2(
                this,
                Invocation.method(#checkServiceStatus, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i3.VoiceServiceStatus>.value(
              _FakeVoiceServiceStatus_2(
                this,
                Invocation.method(#checkServiceStatus, []),
              ),
            ),
          )
          as _i4.Future<_i3.VoiceServiceStatus>);

  @override
  _i4.Future<_i3.VoiceTokenInfo> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<_i3.VoiceTokenInfo>.value(
              _FakeVoiceTokenInfo_1(this, Invocation.method(#refreshToken, [])),
            ),
            returnValueForMissingStub: _i4.Future<_i3.VoiceTokenInfo>.value(
              _FakeVoiceTokenInfo_1(this, Invocation.method(#refreshToken, [])),
            ),
          )
          as _i4.Future<_i3.VoiceTokenInfo>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
