// Mocks generated by Mockito (manually created due to build_runner issues)
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:mockito/mockito.dart' as _i1;
import 'package:ai_bookkeeping/services/tts_service.dart' as _i2;

/// A class which mocks [TTSService].
class MockTTSService extends _i1.Mock implements _i2.TTSService {}
