/*
 * bspatch.h - Binary patch application header
 *
 * Based on bsdiff by Colin Percival
 * Copyright 2003-2005 Colin Percival
 *
 * This implementation is for applying patches generated by bsdiff.
 */

#ifndef BSPATCH_H
#define BSPATCH_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Apply a bsdiff patch to create a new file.
 *
 * @param old_path Path to the original file
 * @param new_path Path to the output (patched) file
 * @param patch_path Path to the patch file
 * @return 0 on success, non-zero error code on failure
 *
 * Error codes:
 *  -1: Cannot open old file
 *  -2: Cannot read old file
 *  -3: Cannot open patch file
 *  -4: Invalid patch header
 *  -5: Patch header corrupt
 *  -6: Cannot decompress ctrl block
 *  -7: Cannot decompress diff block
 *  -8: Cannot decompress extra block
 *  -9: Cannot create new file
 *  -10: Memory allocation failed
 *  -11: Corrupt patch
 */
int bspatch(const char *old_path, const char *new_path, const char *patch_path);

/**
 * Get error message for bspatch error code.
 *
 * @param error_code The error code returned by bspatch
 * @return Human-readable error message
 */
const char* bspatch_strerror(int error_code);

#ifdef __cplusplus
}
#endif

#endif /* BSPATCH_H */
