import 'dart:ui';
import 'package:flutter/widgets.dart' show IconData;
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../core/di/service_locator.dart';
import '../core/contracts/i_database_service.dart';
import '../models/transaction.dart';
import '../models/budget.dart' as model;

/// 简易模式预算服务
///
/// 核心原则：智能默认，无需配置
class SimpleBudgetService {
  final IDatabaseService _db;

  SimpleBudgetService(this._db);

  /// 获取或创建智能预算
  ///
  /// 冷启动时不设置预算，等有数据后再建议
  Future<SimpleBudget> getOrCreateBudget() async {
    // 尝试获取已有预算
    final budgets = await _db.getBudgets();
    final existing = budgets.isNotEmpty ? budgets.first : null;
    if (existing != null) {
      return SimpleBudget(
        monthlyAmount: existing.amount,
        isAutoGenerated: false,
      );
    }

    // 检查是否冷启动
    final transactions = await _db.getTransactions();
    if (transactions.isEmpty) {
      // 冷启动：不设置预算，返回超高默认值（相当于无限制）
      return SimpleBudget(
        monthlyAmount: 999999.0,
        isAutoGenerated: true,
        confidence: 'none',
        isColdStart: true,
      );
    }

    // 有数据：自动生成预算
    return await _generateSmartBudget();
  }

  /// 生成智能预算
  ///
  /// 基于历史数据自动计算合理预算
  Future<SimpleBudget> _generateSmartBudget() async {
    final transactions = await _db.getTransactions();

    if (transactions.isEmpty) {
      // 没有历史数据，使用默认值
      return SimpleBudget(
        monthlyAmount: 3000.0, // 默认3000元
        isAutoGenerated: true,
        confidence: 'low',
      );
    }

    // 计算最近3个月的平均支出
    final now = DateTime.now();
    final threeMonthsAgo = now.subtract(const Duration(days: 90));

    final recentExpenses = transactions.where((t) {
      return t.type == TransactionType.expense &&
          t.date.isAfter(threeMonthsAgo);
    }).toList();

    if (recentExpenses.isEmpty) {
      return SimpleBudget(
        monthlyAmount: 3000.0,
        isAutoGenerated: true,
        confidence: 'low',
      );
    }

    // 计算平均月支出
    final totalExpense = recentExpenses.fold<double>(
      0,
      (sum, t) => sum + t.amount,
    );
    final months = now.difference(threeMonthsAgo).inDays / 30;
    final avgMonthly = totalExpense / months;

    // 加10%缓冲，向上取整到百位
    final suggested = ((avgMonthly * 1.1) / 100).ceil() * 100;

    return SimpleBudget(
      monthlyAmount: suggested.toDouble(),
      isAutoGenerated: true,
      confidence: 'high',
      basedOnMonths: months.round(),
    );
  }

  /// 设置简单预算
  ///
  /// 只需要一个数字：每月能花多少钱
  Future<void> setSimpleBudget(double monthlyAmount) async {
    final now = DateTime.now();
    final budget = model.Budget(
      id: 'simple_${now.millisecondsSinceEpoch}',
      name: '简易月预算',
      amount: monthlyAmount,
      period: model.BudgetPeriod.monthly,
      ledgerId: 'default',
      icon: const IconData(0xe318, fontFamily: 'MaterialIcons'), // Icons.wallet
      color: const Color(0xFF2196F3), // Colors.blue
      createdAt: now,
    );
    await _db.insertBudget(budget);
  }

  /// 获取预算状态（简化版）
  ///
  /// 只返回用户需要知道的信息
  Future<SimpleBudgetStatus> getBudgetStatus() async {
    final budget = await getOrCreateBudget();
    final transactions = await _db.getTransactions();

    // 计算本月支出
    final now = DateTime.now();
    final monthStart = DateTime(now.year, now.month, 1);

    final monthExpenses = transactions.where((t) {
      return t.type == TransactionType.expense &&
          t.date.isAfter(monthStart);
    }).toList();

    final spent = monthExpenses.fold<double>(0, (sum, t) => sum + t.amount);
    final remaining = budget.monthlyAmount - spent;
    final progress = spent / budget.monthlyAmount;

    // 简单的状态判断
    String status;
    if (progress < 0.5) {
      status = '花钱不多';
    } else if (progress < 0.9) {
      status = '花钱正常';
    } else if (progress < 1.0) {
      status = '快超支了';
    } else {
      status = '已经超支';
    }

    return SimpleBudgetStatus(
      budget: budget.monthlyAmount,
      spent: spent,
      remaining: remaining,
      progress: progress,
      status: status,
      shouldWarn: progress >= 0.9,
    );
  }

  /// 获取简单建议
  ///
  /// 基于当前状态给出简单的建议
  Future<String> getSimpleAdvice() async {
    final status = await getBudgetStatus();

    if (status.progress < 0.5) {
      return '这个月花钱不多，继续保持';
    } else if (status.progress < 0.9) {
      return '花钱正常，注意控制';
    } else if (status.progress < 1.0) {
      return '快超支了，少花点钱';
    } else {
      final overspent = status.spent - status.budget;
      return '已经超支${overspent.toInt()}元了';
    }
  }
}

/// 简单预算模型
class SimpleBudget {
  final double monthlyAmount;
  final bool isAutoGenerated;
  final String confidence; // 'none', 'low', 'medium', 'high'
  final int? basedOnMonths;
  final bool isColdStart; // 是否冷启动状态

  SimpleBudget({
    required this.monthlyAmount,
    required this.isAutoGenerated,
    this.confidence = 'medium',
    this.basedOnMonths,
    this.isColdStart = false,
  });

  String getExplanation() {
    if (isColdStart) {
      return '先用几天，再设置预算';
    }

    if (!isAutoGenerated) {
      return '您设置的预算';
    }

    if (confidence == 'low') {
      return '系统建议的预算（可以修改）';
    }

    return '基于最近${basedOnMonths}个月的花费';
  }
}

/// 简单预算状态
class SimpleBudgetStatus {
  final double budget;
  final double spent;
  final double remaining;
  final double progress;
  final String status;
  final bool shouldWarn;

  SimpleBudgetStatus({
    required this.budget,
    required this.spent,
    required this.remaining,
    required this.progress,
    required this.status,
    required this.shouldWarn,
  });
}


/// Provider
final simpleBudgetServiceProvider = Provider<SimpleBudgetService>((ref) {
  return SimpleBudgetService(sl<IDatabaseService>());
});
