// Mocks generated by Mockito 5.4.6 from annotations
// in ai_bookkeeping/test/services/voice/voice_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:typed_data' as _i6;
import 'dart:ui' as _i4;

import 'package:ai_bookkeeping/services/tts_service.dart' as _i5;
import 'package:ai_bookkeeping/services/voice/entity_disambiguation_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDisambiguationResult_0 extends _i1.SmartFake
    implements _i2.DisambiguationResult {
  _FakeDisambiguationResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EntityDisambiguationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEntityDisambiguationService extends _i1.Mock
    implements _i2.EntityDisambiguationService {
  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Future<_i2.DisambiguationResult> disambiguate(
    String? userInput, {
    required _i2.TransactionQueryCallback? queryCallback,
    _i2.DisambiguationContext? context,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #disambiguate,
              [userInput],
              {#queryCallback: queryCallback, #context: context},
            ),
            returnValue: _i3.Future<_i2.DisambiguationResult>.value(
              _FakeDisambiguationResult_0(
                this,
                Invocation.method(
                  #disambiguate,
                  [userInput],
                  {#queryCallback: queryCallback, #context: context},
                ),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.DisambiguationResult>.value(
                  _FakeDisambiguationResult_0(
                    this,
                    Invocation.method(
                      #disambiguate,
                      [userInput],
                      {#queryCallback: queryCallback, #context: context},
                    ),
                  ),
                ),
          )
          as _i3.Future<_i2.DisambiguationResult>);

  @override
  void recordRecentOperation(_i2.TransactionRecord? record) =>
      super.noSuchMethod(
        Invocation.method(#recordRecentOperation, [record]),
        returnValueForMissingStub: null,
      );

  @override
  void updateContext(_i2.DisambiguationContext? context) => super.noSuchMethod(
    Invocation.method(#updateContext, [context]),
    returnValueForMissingStub: null,
  );

  @override
  void clearContext() => super.noSuchMethod(
    Invocation.method(#clearContext, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<_i2.DisambiguationResult> handleClarification(
    String? userInput,
    List<_i2.ScoredCandidate>? candidates,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#handleClarification, [userInput, candidates]),
            returnValue: _i3.Future<_i2.DisambiguationResult>.value(
              _FakeDisambiguationResult_0(
                this,
                Invocation.method(#handleClarification, [
                  userInput,
                  candidates,
                ]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.DisambiguationResult>.value(
                  _FakeDisambiguationResult_0(
                    this,
                    Invocation.method(#handleClarification, [
                      userInput,
                      candidates,
                    ]),
                  ),
                ),
          )
          as _i3.Future<_i2.DisambiguationResult>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [TTSEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockTTSEngine extends _i1.Mock implements _i5.TTSEngine {
  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speak(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> resume() =>
      (super.noSuchMethod(
            Invocation.method(#resume, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setRate(double? rate) =>
      (super.noSuchMethod(
            Invocation.method(#setRate, [rate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setLanguage(String? language) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguage, [language]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVoice(String? voiceName) =>
      (super.noSuchMethod(
            Invocation.method(#setVoice, [voiceName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.TTSVoice>> getAvailableVoices() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableVoices, []),
            returnValue: _i3.Future<List<_i5.TTSVoice>>.value(<_i5.TTSVoice>[]),
            returnValueForMissingStub: _i3.Future<List<_i5.TTSVoice>>.value(
              <_i5.TTSVoice>[],
            ),
          )
          as _i3.Future<List<_i5.TTSVoice>>);

  @override
  _i3.Future<_i6.Uint8List?> synthesize(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#synthesize, [text]),
            returnValue: _i3.Future<_i6.Uint8List?>.value(),
            returnValueForMissingStub: _i3.Future<_i6.Uint8List?>.value(),
          )
          as _i3.Future<_i6.Uint8List?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
