// Mocks generated by Mockito (manually created due to build_runner issues)
// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;
import 'dart:typed_data' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:record/record.dart' as _i4;
import 'package:ai_bookkeeping/services/voice_recognition_engine.dart' as _i5;
import 'package:ai_bookkeeping/services/tts_service.dart' as _i6;

/// A class which mocks [VoiceRecognitionEngine].
class MockVoiceRecognitionEngine extends _i1.Mock
    implements _i5.VoiceRecognitionEngine {}

/// A class which mocks [TTSService].
class MockTTSService extends _i1.Mock implements _i6.TTSService {}

/// A class which mocks [AudioRecorder].
class MockAudioRecorder extends _i1.Mock implements _i4.AudioRecorder {}
